/**
 * Done lines plugin for IITC Next
 *
 * Highlight done lines drawn by the draw lines plugin.
 * safeWindow is provided for access to the IITC Next core components.
 *
 * This plugin is generated by Codex.
 */

import "../types/iitc.ts";
import * as Cesium from "cesium";
import { IITCCore } from "../types/iitc";
import { safeWindow } from "../utils/window";

const DRAW_LINES_LAYER_NAME = "Draw Lines";
const LINK_LAYER_NAMES = ["links-enlightened", "links-resistance", "links-machina", "links-neutral"];
const HIGHLIGHT_WIDTH = 4;
const DASH_LENGTH = 6;
const POSITION_EPSILON = 1e-6;

interface Point {
  lng: number;
  lat: number;
}

type Segment = [Point, Point];

interface LineStyle {
  material: Cesium.MaterialProperty;
  width: Cesium.Property | undefined;
  doneMaterial?: Cesium.PolylineDashMaterialProperty;
}

interface DrawLineSegment {
  entity: Cesium.Entity;
  segment: Segment;
}

class DoneLinesPlugin {
  public id = "done-lines";
  public name = "Done Lines";
  public description = "Highlight draw lines that match existing map links.";

  private viewer: IITCCore["viewer"];
  private logManager: IITCCore["logManager"];
  private layerManager: IITCCore["layerManager"];

  private drawLinesSource: Cesium.CustomDataSource | undefined;
  private updateQueued = false;
  private trackedSources: Set<Cesium.DataSource> = new Set();
  private originalLineStyles: Map<Cesium.Entity, LineStyle> = new Map();
  private entityCollectionChangedListener: Cesium.EntityCollection.CollectionChangedEventCallback = (_collection, _added, removed) => {
    removed.forEach(entity => this.restoreLineStyle(entity));
    this.scheduleUpdate();
  };
  private dataSourceAddedListener = (source: Cesium.DataSource) => this.trackSource(source);
  private dataSourceRemovedListener = (source: Cesium.DataSource) => this.untrackSource(source);

  public init() {
    if (safeWindow) {
      const iitc: IITCCore = safeWindow.iitc;
      this.viewer = iitc.viewer!;
      this.logManager = iitc.logManager!;
      this.layerManager = iitc.layerManager!;
    }

    if (!this.viewer || !this.logManager || !this.layerManager) {
      console.warn("[WARN][DoneLinesPlugin] IITC Next core components missing", {
        viewer: !!this.viewer,
        logManager: !!this.logManager,
        layerManager: !!this.layerManager,
      });
      return;
    }

    this.drawLinesSource = this.layerManager.getOrCreateOverlay(DRAW_LINES_LAYER_NAME);
    const layerManager = this.layerManager;
    this.viewer.dataSources.dataSourceAdded.addEventListener(this.dataSourceAddedListener);
    this.viewer.dataSources.dataSourceRemoved.addEventListener(this.dataSourceRemovedListener);
    this.trackSource(this.drawLinesSource);
    LINK_LAYER_NAMES.forEach(name => this.trackSource(layerManager.getOrCreateDataSource(name)));
    this.forEachDataSource(source => this.trackSource(source));
    this.scheduleUpdate();
  }

  public deinit() {
    this.viewer?.dataSources.dataSourceAdded.removeEventListener(this.dataSourceAddedListener);
    this.viewer?.dataSources.dataSourceRemoved.removeEventListener(this.dataSourceRemovedListener);
    this.trackedSources.forEach(source => this.untrackSource(source));
    this.trackedSources.clear();
    this.restoreAllLineStyles();
    this.drawLinesSource = undefined;
    this.updateQueued = false;
  }

  private forEachDataSource(callback: (source: Cesium.DataSource) => void) {
    if (!this.viewer) return;

    const sources = this.viewer.dataSources;
    for (let i = 0; i < sources.length; i++) {
      callback(sources.get(i));
    }
  }

  private trackSource(source: Cesium.DataSource) {
    if (!this.isRelevantSource(source) || this.trackedSources.has(source)) return;

    source.entities.collectionChanged.addEventListener(this.entityCollectionChangedListener);
    this.trackedSources.add(source);
    this.scheduleUpdate();
  }

  private untrackSource(source: Cesium.DataSource) {
    if (!this.trackedSources.has(source)) return;

    if (source.name === DRAW_LINES_LAYER_NAME) {
      source.entities.values.forEach(entity => this.restoreLineStyle(entity));
    }
    source.entities.collectionChanged.removeEventListener(this.entityCollectionChangedListener);
    this.trackedSources.delete(source);
    this.scheduleUpdate();
  }

  private isRelevantSource(source: Cesium.DataSource): boolean {
    return source.name === DRAW_LINES_LAYER_NAME || LINK_LAYER_NAMES.includes(source.name);
  }

  private scheduleUpdate() {
    if (this.updateQueued) return;

    this.updateQueued = true;
    requestAnimationFrame(() => {
      this.updateQueued = false;
      this.updateHighlights();
    });
  }

  private updateHighlights() {
    if (!this.viewer) return;

    const drawLineSegments = this.getDrawLineSegments();
    if (drawLineSegments.length === 0) {
      this.restoreAllLineStyles();
      this.viewer.scene.requestRender();
      return;
    }

    const linkSegments = this.getLinkSegments();
    const doneLines = new Set<Cesium.Entity>();

    drawLineSegments.forEach(drawLine => {
      if (linkSegments.some(link => this.segmentsMatch(drawLine.segment, link))) {
        doneLines.add(drawLine.entity);
      }
    });

    this.originalLineStyles.forEach((_, line) => {
      if (!doneLines.has(line)) this.restoreLineStyle(line);
    });
    doneLines.forEach(line => this.applyDoneStyle(line));

    this.viewer.scene.requestRender();
  }

  private getDrawLineSegments(): DrawLineSegment[] {
    const segments: DrawLineSegment[] = [];

    this.drawLinesSource?.entities.values.forEach(entity => {
      const positions = entity.polyline?.positions?.getValue(Cesium.JulianDate.now()) as Cesium.Cartesian3[] | undefined;
      if (!positions || positions.length < 2) return;

      for (let i = 0; i < positions.length - 1; i++) {
        const a = this.toPoint(positions[i]);
        const b = this.toPoint(positions[i + 1]);
        if (a && b) segments.push({ entity, segment: [a, b] });
      }
    });
    return segments;
  }

  private getLinkSegments(): Segment[] {
    const segments: Segment[] = [];

    this.forEachLink(link => {
      const segment = this.getPolylineSegment(link);
      if (segment) segments.push(segment);
    });

    return segments;
  }

  private forEachLink(callback: (link: Cesium.Entity) => void) {
    this.forEachDataSource(source => {
      if (!LINK_LAYER_NAMES.includes(source.name)) return;
      source.entities.values.forEach(entity => {
        if (entity.polyline) callback(entity);
      });
    });
  }

  private getPolylineSegment(entity: Cesium.Entity): Segment | undefined {
    const positions = entity.polyline?.positions?.getValue(Cesium.JulianDate.now()) as Cesium.Cartesian3[] | undefined;
    if (!positions || positions.length < 2) return;

    const a = this.toPoint(positions[0]);
    const b = this.toPoint(positions[1]);
    if (!a || !b) return;

    return [a, b];
  }

  private toPoint(position: Cesium.Cartesian3): Point | undefined {
    const cartographic = Cesium.Cartographic.fromCartesian(position);
    if (!cartographic) return;

    return {
      lng: Cesium.Math.toDegrees(cartographic.longitude),
      lat: Cesium.Math.toDegrees(cartographic.latitude),
    };
  }

  private segmentsMatch(a: Segment, b: Segment): boolean {
    return (
      this.pointsMatch(a[0], b[0]) && this.pointsMatch(a[1], b[1])
    ) || (
      this.pointsMatch(a[0], b[1]) && this.pointsMatch(a[1], b[0])
    );
  }

  private pointsMatch(a: Point, b: Point): boolean {
    return Math.abs(a.lng - b.lng) <= POSITION_EPSILON &&
      Math.abs(a.lat - b.lat) <= POSITION_EPSILON;
  }

  private applyDoneStyle(line: Cesium.Entity) {
    if (!line.polyline) return;

    const currentMaterial = line.polyline.material;
    const currentWidth = line.polyline.width;
    const existingStyle = this.originalLineStyles.get(line);
    if (existingStyle && currentMaterial === existingStyle.doneMaterial) return;

    const materialChangedExternally = existingStyle && currentMaterial !== existingStyle.doneMaterial;
    const originalStyle = existingStyle && !materialChangedExternally
      ? existingStyle
      : {
        material: currentMaterial,
        width: currentWidth,
      };
    const doneMaterial = new Cesium.PolylineDashMaterialProperty({
      color: this.getMaterialColor(originalStyle.material).withAlpha(1),
      dashLength: DASH_LENGTH,
    });

    this.originalLineStyles.set(line, {
      ...originalStyle,
      doneMaterial,
    });
    line.polyline.material = doneMaterial;
    line.polyline.width = new Cesium.ConstantProperty(HIGHLIGHT_WIDTH);
  }

  private restoreAllLineStyles() {
    Array.from(this.originalLineStyles.keys()).forEach(line => this.restoreLineStyle(line));
  }

  private restoreLineStyle(line: Cesium.Entity) {
    const originalStyle = this.originalLineStyles.get(line);
    if (!originalStyle || !line.polyline) return;

    line.polyline.material = originalStyle.material;
    line.polyline.width = originalStyle.width;
    this.originalLineStyles.delete(line);
  }

  private getMaterialColor(material: Cesium.MaterialProperty): Cesium.Color {
    const now = Cesium.JulianDate.now();
    const colorProperty = material instanceof Cesium.ColorMaterialProperty
      ? material.color
      : undefined;
    const color = colorProperty?.getValue(now);

    return color instanceof Cesium.Color ? color : Cesium.Color.WHITE;
  }
}

const register = () => {
  if (safeWindow && safeWindow.iitc && safeWindow.iitc.pluginManager) {
    safeWindow.iitc.pluginManager.registerPlugin(new DoneLinesPlugin());
  } else {
    setTimeout(register, 1000);
  }
};

register();
